services:
  web:
    container_name: purjayadi-website
    image: nginx:alpine
    ports:
      - "purjayadi-website:8085:80"
    volumes:
      - .:/usr/share/nginx/html:ro
    networks:
      - npm

networks:
  npm:
    external: true
