<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_front extends CI_Model
{
    public function getfront(){
    $this->db->where('tampil','ya');
    $get_front = $this->db->get('kategori');
    return $get_front->result();
    }
}

/* End of file Kategori.php */
/* Location: ./application/controllers/Kategori.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-07 08:52:36 */
/* http://harviacode.com */