<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Wa_order_model extends CI_Model
{

    public $table = 'wa_order';
    public $id = 'idwa_order';
    public $order = 'DESC';
    public $url_redirect = 'url_redirect';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('username', $this->session->identity);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->where('username', $this->session->identity);
        return $this->db->get($this->table)->row();
    }
    
  

}

/* End of file Wa_order_model.php */
/* Location: ./application/models/Wa_order_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-14 08:05:41 */
/* http://harviacode.com */