<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_bpage extends CI_Model
{
    public function getbpage(){
      $this->db->where('username', $this->session->identity);
    $get_bpage = $this->db->get('b_ppage');
    return $get_bpage->result();
  }

  public function insertdata($data){
    $insert_data = $this->db->insert('b_ppage',$data);
    return $insert_data;
  }

  public function editbpage($id){
    $this->db->where('id_bpage',$id);
    $this->db->where('username', $this->session->identity);
    $edit_bpage = $this->db->get('b_ppage');
    return $edit_bpage;
  }

  public function updatedata($id,$data){
        $this->db->where('id_bpage',$id);
        $this->db->where('username', $this->session->identity);
        $update_data = $this->db->update('b_ppage',$data);
        return $update_data;
  }

  public function deletedata($id){
    $this->db->where('id_bpage',$id);
    $this->db->where('username', $this->session->identity);
    $delete_data = $this->db->delete('b_ppage');
    return $delete_data;
  }

  public function get_byid($id){
    $this->db->where('id_bpage',$id);
    $this->db->where('username', $this->session->identity);
    $lpage_byid = $this->db->get('b_ppage');
    return $lpage_byid;
  }

}

/* End of file Kategori_model.php */
/* Location: ./application/models/Kategori_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-07 08:52:36 */
/* http://harviacode.com */