<?php

if (!defined('BASEPATH')) exit('No direct script access allowed');

class Model_menu extends CI_Model
{

  public function getmenu(){
    
    $this->db->where('username', $this->session->identity);
    return $this->db->get('menu')->result();
  }

  public function jmlData(){
    $this->db->where('username', $this->session->identity);
    return $this->db->get('menu')->num_rows();  //utk pagination
  }

  public function insertdata($data){
    $insert_data = $this->db->insert('menu',$data);
    return $insert_data;
  }

  public function editmenu($id){
  	$this->db->where('id_menu',$id);
    $this->db->where('username', $this->session->identity);
  	$edit_menu 	= $this->db->get('menu');
  	return $edit_menu;
  }

  public function updatedata($id,$data){
  		$this->db->where('id_menu',$id);
      $this->db->where('username', $this->session->identity);
  		$update_data = $this->db->update('menu',$data);
  		return $update_data;
  }

  public function deletedata($id){
  	$this->db->where('id_menu',$id);
    $this->db->where('username', $this->session->identity);
    $delete = $this->db->get('menu');
    $row = $delete->row();
    unlink("./assets/imgmenu/$row->gambar");
    $hapus = $this->db->delete('menu', array('id_menu' => $id));
    return $hapus;

  	/*$delete_data = $this->db->delete('menu');
  	return $delete_data;*/
  }

  public function getmenubyid($id){
    $this->db->where('id_menu',$id);
    $menu_byid = $this->db->get('menu');
    return $menu_byid;
  }

}

/* End of file Menu_model.php */
/* Location: ./application/models/Menu_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-07 03:56:07 */
/* http://harviacode.com */