<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_kategori extends CI_Model
{
    public function getkategori(){
    $this->db->where('username', $this->session->identity);
    $get_kategori = $this->db->get('kategori');
    return $get_kategori->result();
  }

  public function insertdata($data){
    $insert_data = $this->db->insert('kategori',$data);
    return $insert_data;
  }

  public function editkategori($id){
    $this->db->where('id_kategori',$id);
    $this->db->where('username', $this->session->identity);
    $edit_kategori  = $this->db->get('kategori');
    return $edit_kategori;
  }

  public function updatedata($id,$data){
        $this->db->where('id_kategori',$id);
        $this->db->where('username', $this->session->identity);
        $update_data = $this->db->update('kategori',$data);
        return $update_data;
  }

  public function get_byid($id){
    $this->db->where('id_kategori',$id);
    $this->db->where('username', $this->session->identity);
    $kategori_byid = $this->db->get('kategori');
    return $kategori_byid;
  }

}

/* End of file Kategori_model.php */
/* Location: ./application/models/Kategori_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-07 08:52:36 */
/* http://harviacode.com */