<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_lpage extends CI_Model
{
    public function getlpage(){
      $this->db->where('username', $this->session->identity);
    $get_lpage = $this->db->get('link_ppage');
    return $get_lpage->result();
  }

  public function insertdata($data){
    $insert_data = $this->db->insert('link_ppage',$data);
    return $insert_data;
  }

  public function editlpage($id){
    $this->db->where('id_ppage',$id);
    $this->db->where('username', $this->session->identity);
    $edit_lpage = $this->db->get('link_ppage');
    return $edit_lpage;
  }

  public function updatedata($id,$data){
        $this->db->where('id_ppage',$id);
        $this->db->where('username', $this->session->identity);
        $update_data = $this->db->update('link_ppage',$data);
        return $update_data;
  }

  public function deletedata($id){
    $this->db->where('id_ppage',$id);
    $this->db->where('username', $this->session->identity);
    $delete_data = $this->db->delete('link_ppage');
    return $delete_data;
  }

  public function get_byid($id){
    $this->db->where('id_ppage',$id);
    $this->db->where('username', $this->session->identity);
    $lpage_byid = $this->db->get('link_ppage');
    return $lpage_byid;
  }

}

/* End of file Kategori_model.php */
/* Location: ./application/models/Kategori_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-07 08:52:36 */
/* http://harviacode.com */