<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_artikel extends CI_Model
{
    public function getartikel(){
      $this->db->where('username', $this->session->identity);
    $get_artikel = $this->db->get('artikel');
    return $get_artikel->result();
  }

  public function insertdata($data){
    $insert_data = $this->db->insert('artikel',$data);
    return $insert_data;
  }

  public function editartikel($id){
    $this->db->where('id_artikel',$id);
    $this->db->where('username', $this->session->identity);
    $edit_artikel = $this->db->get('artikel');
    return $edit_artikel;
  }

  public function updatedata($id,$data){
        $this->db->where('id_artikel',$id);
        $this->db->where('username', $this->session->identity);
        $update_data = $this->db->update('artikel',$data);
        return $update_data;
  }

  public function deletedata($id){
    $this->db->where('id_artikel',$id);
    $this->db->where('username', $this->session->identity);
    $delete = $this->db->get('artikel');
    $row = $delete->row();
    unlink("./assets/imgartikel/$row->gambar");
    $hapus = $this->db->delete('artikel', array('id_artikel' => $id));
    return $hapus;
    /*$delete_data = $this->db->delete('artikel');
    return $delete_data;*/
  }

  public function get_byid($id){
    $this->db->where('id_artikel',$id);
    $this->db->where('username', $this->session->identity);
    $artikel_byid = $this->db->get('artikel');
    return $artikel_byid;
  }

}

/* End of file Kategori_model.php */
/* Location: ./application/models/Kategori_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-07 08:52:36 */
/* http://harviacode.com */