<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_widget extends CI_Model
{
    public function getwidget(){
      $this->db->where('username', $this->session->identity);
    $get_widget = $this->db->get('widget');
    return $get_widget->result();
  }

  public function insertdata($data){
    $insert_data = $this->db->insert('widget',$data);
    return $insert_data;
  }

  public function editwidget($id){
    $this->db->where('id_widget',$id);
    $this->db->where('username', $this->session->identity);
    $edit_widget = $this->db->get('widget');
    return $edit_widget;
  }

  public function updatedata($id,$data){
        $this->db->where('id_widget',$id);
        $this->db->where('username', $this->session->identity);
        $update_data = $this->db->update('widget',$data);
        return $update_data;
  }

  public function deletedata($id){
    $this->db->where('id_widget',$id);
    $this->db->where('username', $this->session->identity);
    $delete_data = $this->db->delete('widget');
    return $delete_data;
  }
}

/* End of file Kategori_model.php */
/* Location: ./application/models/Kategori_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-07 08:52:36 */
/* http://harviacode.com */