<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_bheader extends CI_Model
{
    public function getbheader(){
      $this->db->where('username', $this->session->identity);
    $get_bheader = $this->db->get('b_header');
    return $get_bheader->result();
  }

  public function insertdata($data){

    $insert_data = $this->db->insert('b_header',$data);
    return $insert_data;
  }

  public function editbheader($id){
    $this->db->where('id_bheader',$id);
    $this->db->where('username', $this->session->identity);
    $edit_bheader = $this->db->get('b_header');
    return $edit_bheader;
  }

  public function updatedata($id,$data){
        $this->db->where('id_bheader',$id);
        $this->db->where('username', $this->session->identity);
        $update_data = $this->db->update('b_header',$data);
        return $update_data;
  }

  public function deletedata($id){
    $this->db->where('id_bheader',$id);
    $this->db->where('username', $this->session->identity);
    $delete_data = $this->db->delete('b_header');
    return $delete_data;
  }
}

/* End of file Kategori_model.php */
/* Location: ./application/models/Kategori_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-07 08:52:36 */
/* http://harviacode.com */