<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_gambar extends CI_Model
{
    public function getgambar(){
      $this->db->where('username', $this->session->identity);
    $get_gambar = $this->db->get('gambar');
    return $get_gambar->result();
  }

  public function insertdata($data){
    $insert_data = $this->db->insert('gambar',$data);
    return $insert_data;
  }

  public function editgambar($id){
    $this->db->where('id_gambar',$id);
    $this->db->where('username', $this->session->identity);
    $edit_gambar = $this->db->get('gambar');
    return $edit_gambar;
  }

  public function updatedata($id,$data){
        $this->db->where('id_gambar',$id);
        $this->db->where('username', $this->session->identity);
        $update_data = $this->db->update('gambar',$data);
        return $update_data;
  }

  public function deletedata($id){
    $this->db->where('id_gambar',$id);
    $this->db->where('username', $this->session->identity);
    $delete = $this->db->get('gambar');
    $row = $delete->row();
    unlink("./assets/imgpicture/$row->gambar");
    $hapus = $this->db->delete('gambar', array('id_gambar' => $id));
    return $hapus;

    /*$delete_data = $this->db->delete('gambar');
    return $delete_data;*/
  }

  public function get_byid($id){
    $this->db->where('id_gambar',$id);
    $this->db->where('username', $this->session->identity);
    $artikel_byid = $this->db->get('gambar');
    return $artikel_byid;
  }

}

/* End of file Kategori_model.php */
/* Location: ./application/models/Kategori_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-07 08:52:36 */
/* http://harviacode.com */