<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Key_ahiran_model extends CI_Model
{

    public $table = 'key_ahiran';
    public $id = 'idkey_ahiran';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('username', $this->session->identity);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->where('username', $this->session->identity);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
    	$this->db->or_like('keyword', $q);
        $this->db->where('username', $this->session->identity);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
    	$this->db->or_like('keyword', $q);
        $this->db->where('username', $this->session->identity);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->where('username', $this->session->identity);
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->where('username', $this->session->identity);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->where('username', $this->session->identity);
        $this->db->delete($this->table);
    }

}

/* End of file Key_ahiran_model.php */
/* Location: ./application/models/Key_ahiran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-13 03:47:39 */
/* http://harviacode.com */